/* test #3
 * testing how let-er works
 */

try{throw (a['foo'] * 2, a == 8)}catch (b) {try{throw void 0}catch (c) {try{throw /3*/ig}catch (d) {
	console.log(b);
}}}
